$Step-1$:
    
**Import required packages**

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

$Step-2$:
 
**Read the data**

In [53]:
salary_df = pd.read_csv("Salary_Data.csv")
salary_df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [5]:
salary_df.shape

(30, 2)

In [6]:
salary_df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [9]:
salary_df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [10]:
salary_df.dtypes

YearsExperience    float64
Salary               int64
dtype: object

$Step-3$

**Divide data into input and output data**

In [24]:
X=salary_df.drop('Salary',axis=1)
y=salary_df['Salary']

$Step-4$

**Divide data into train and test**

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=1234,test_size=0.30)

In [28]:
X_train.shape, X_test.shape

((21, 1), (9, 1))

In [29]:
y_train.shape, y_test.shape

((21,), (9,))

In [16]:
X_train.head()

13    4.1
22    7.9
24    8.7
0     1.1
2     1.5
Name: YearsExperience, dtype: float64

$Step-5$

**Model development**

In [18]:
X_train.shape

(21,)

In [19]:
salary_df.shape

(30, 2)

In [20]:
salary_df.ndim

2

In [30]:
X_train.ndim

2

In [32]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

$Step-6$

**Model predictions**

In [33]:
y_predictions=LR.predict(X_test)

In [36]:
y_predictions

array([ 55630.13259001,  62221.33017291,  46214.136043  ,  37739.7391507 ,
       122483.70807372,  55630.13259001,  44330.9367336 , 102710.11532501,
        67870.92810111])

$Step-7$

**Model evaluation**

In [38]:
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.metrics import mean_absolute_error
mse=mean_squared_error(y_test,y_predictions)
mae=mean_absolute_error(y_test,y_predictions)
r2=r2_score(y_test,y_predictions)
rmse=np.sqrt(mse)

print("R-sqaure:",r2)
print("MSE:",mse)
print("MAE:",mae)
print("RMSE:",rmse)

R-sqaure: 0.949721948148016
MSE: 40149896.466138825
MAE: 4949.502700312147
RMSE: 6336.39459520466


$Step-8$

**Finding coeffiecnt and Intercept**

In [39]:
LR.coef_

array([9415.996547])

In [40]:
LR.intercept_

25498.943639602097

$Step-9$:
    
**Save the model**

In [41]:
import pickle
pickle.dump(LR,open("linear_salary_model.pkl","wb"))

$Step-10$:
    
**Load the model**

In [42]:
import pickle
salary_model=pickle.load(open("linear_salary_model.pkl","rb"))
salary_model

LinearRegression()

$Step-11$:
    
**Predictions**

In [43]:
X_test

YearsExperience
7               3.2
10              3.9
4               2.2
1               1.3
28             10.3
8               3.2
3               2.0
23              8.2
14              4.5

In [44]:
X_test.values

array([[ 3.2],
       [ 3.9],
       [ 2.2],
       [ 1.3],
       [10.3],
       [ 3.2],
       [ 2. ],
       [ 8.2],
       [ 4.5]])

In [45]:
len(X_test.columns)

1

In [50]:
salary_model.predict([[1]])

array([34914.9401866])

In [51]:
salary_model.predict(X_test)

array([ 55630.13259001,  62221.33017291,  46214.136043  ,  37739.7391507 ,
       122483.70807372,  55630.13259001,  44330.9367336 , 102710.11532501,
        67870.92810111])